### PR TITLE
make comments reflect the functions they're about

### PR DESCRIPTION
**Pull request by mmckinst**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @mmckinst

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by mmckinst** [comment]
wat. is the CLA needed for trivial patches like mine?

**Comment by mmckinst** [comment]
This should fall under the obvious fix rule.

https://docs.chef.io/community_contributions.html#the-obvious-fix-rule

> very small contributions such as fixing spelling errors, where the content is small enough to not be considered intellectual property, can be submitted by a contributor as a patch, without a CLA. If you submit an obvious fix without first signing a contributor license agreement, then you are agreeing that your submission is not independently copyrightable.


https://docs.chef.io/community_contributions.html#what-qualifies-as-an-obvious-fix

> ...some likely examples include the following
> * Cleaning up comments in the code

**Comment by patrick-wright** [comment]
Thanks, @mmckinst.  The CLA notice is automated, and this change does fall under the obvious fix rule.

**Pull request merged**
