### PR TITLE
WIP: Use buildkite for PR verification

### PR DESCRIPTION
**Pull request by jaymalasinha**
Signed-off-by: Jaymala Sinha <jsinha@chef.io>

### CODE REVIEW

**Comment by coderanger** [comment]
Do we want to talk about this? Is buildkite accessible to the public somewhere?

**Comment by coderanger** [comment]
@schisamo We still need to have a public discussion and make sure this is a community consensus :)

**Comment by thommay** [comment]
Hey Noah,
we'll absolutely have a discussion about moving our open source projects to Build Kite as and when that's appropriate. In the same way that I had a chef/chef PR open for much of the spring experimenting with CircleCI, this one allows us to investigate what moving to BK entails.
It's worth remembering that Travis and AppVeyor aren't free, and the choice of CI systems have both a financial and a support burden, all of which is borne by Chef Software. We're happy to continue to do that, but the choice of which CI system is used has to make sense for us. We're moving to Build Kite for our commercial projects because it allows us to consolidate Windows, Linux and more esoteric platforms in one place, and has a more responsive support structure that allows us to deal with problems quicker.
Publicly accessible builds are a total blocker to us using BK for our open source projects, and we're working with the BK folks to ensure that happens. 
Hope this clarifies what's happening and what will happen next.

**Comment by tas50** [comment]
I'm going to close this out since there's conflicts and things have changed since it was originally opened.

**Pull request closed without merging**
