### PR TITLE
Artifactory queries use package_name instead of product_name

### PR DESCRIPTION
**Pull request by patrick-wright**
Maps `product_name` to `Product` `package_names` when querying packages in artifactory.  I don't believe this change will be necessary for bintray or omnitruck backends.

@schisamo @sersut

### CODE REVIEW

**Comment by patrick-wright** [comment]
https://github.com/chef-cookbooks/chef-ingredient/issues/100

**Comment by patrick-wright** [comment]
Tested change with chef-ingredient:
```ruby

chef_ingredient 'compliance' do
  action :install
  channel :stable
  version :latest
end

chef_ingredient 'compliance' do
  action :upgrade
  channel :unstable
  version :latest
end
```

kitchen log snippet:
```
 - install version 1.1.2-1 of package chef-compliance

       Recipe: test::compliance
         * chef_ingredient[compliance] action upgrade
           - Download compliance package from http://artifactory.chef.co/omnibus-unstable-local/com/getchef/chef-compliance/1.1.1/ubuntu/14.04/chef-compliance_1.1.1-1_amd64.deb
```

**Comment by patrick-wright** [comment]
@alexpop fyi

**Comment by sersut** [comment]
👍

**Pull request merged**
