### PR TITLE
Add no_proxy support to the install.ps1 script

### PR DESCRIPTION
**Pull request by Romascopa**
added no_proxy support

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by Romascopa** [comment]
I can't get a DCO submitted. The git clone feature isn't working properly for this repo. If I  clone and push nothing it wants to delete a ton of files for some reason. Not sure a way around it and don't want to do those deletions. Just the 1 file edit.

**Comment by miah** [comment]
To submit a DCO, just make sure the last line of your commit includes a sign-off:

```
[miah@awakening inspec]$ git config -l|grep template
commit.template=~/.config/git/git-commit-template
[miah@awakening inspec]$ 
[miah@awakening inspec]$ cat ~/.config/git/git-commit-template 

Signed-off-by: Miah Johnson <miah@chia-pet.org>
```

**Comment by Romascopa** [comment]
Thanks for pro tip. I'll set mine up.

Cheers,
Lance

**Comment by tas50** [comment]
@Romascopa Any chance you can get the DCO on this one?

**Comment by tas50** [comment]
Fixed in #299

**Pull request closed without merging**
