### PR TITLE
actually copy the appx install instead of linking

### PR DESCRIPTION
**Pull request by mwrock**
We have noticed nano installs failing on azure nano instances as well as local images built differently from our packer template. There are issues with the ACLs of the appx deployed location that prevent chef from being able to be invoked.

I'd like to believe this is either a bug or an error on our part but documentation here is extremely scarce and I am trying to contact someone at microsoft for some more detailed guidance. If it is by design we may have to eventually move to .zip based installeds but I'm skeptical it will come to that.

In the meantime, this PR simply copies the bits from the appx directory to the omnibus root location instead of just linking to the original location.

### CODE REVIEW

**Comment by mwrock** [comment]
cc @chef/engineering-services

**Comment by scotthain** [comment]
Ouch :( 👍 gotta do what you gotta do.

**Comment by mwrock** [comment]
I've emailed some contacts at MS and also have opened this forum post: https://social.technet.microsoft.com/Forums/windowsserver/en-US/1f0c7e48-ba68-40e4-bfe5-1215dba3b465/receiving-1073741790-invoking-ruby-on-azure-tp5-but-works-fine-on-locally-built-tp5-nano-vm?forum=NanoServer

**Comment by mwrock** [comment]
Just to note: Microsoft is aware of this issue and the workaround in this pr is the best approach at this time. A future release will support a better security model for our scenario.

**Pull request merged**
