### PR TITLE
Added support for retrying project msi installation for exit code 1618

### PR DESCRIPTION
**Pull request by gshively11**
Similar to https://github.com/chef/mixlib-install/pull/110, this adds a retry mechanism for project installs on Windows when encountering a 1618 error code (another msi installation is in progress).  The previous pull request fixed this issue for installing the chef client, but I'm encountering it once again when installing the push jobs client via the push-jobs cookbook (which depends on chef-ingredient, which depends on mixlib-install).  I'm in the process of testing this out on our stack, I will report back once I've confirmed it fixes the problem.  Submitting this prior to that confirmation to get some early feedback.

### CODE REVIEW

**Comment by gshively11** [comment]
First attempt appears successful, although the 1618 code did not occur every time in the past, so I'll continue to run through some tests.

**Comment by sersut** [comment]
👍

**Comment by mwrock** [comment]
:+1:

**Comment by schisamo** [comment]
:shipit:

**Pull request merged**
