### PR TITLE
sizing of install_command.ps1 < 3040bytes when interpolated

### PR DESCRIPTION
**Pull request by hh**
These changes to human messages where the quickest way to reduce the size.
I'm sure someone proficient in PowerShell could do much better.

### CODE REVIEW

**Comment by hh** [comment]
Should fix chef/mixlib-install#6  chef/knife-windows#262 and chef/chef-provisioning#431

**Comment by thommay** [comment]
I appreciate that this is a tricky and annoying problem, but I believe the right solution is to figure out a sustainable approach cross versions (this is broken on win2k8 for different reasons, involving memory limits on powershell sessions). To the best of my knowledge knife-windows doesn't (yet) use mixlib-install.

Also, to make this more annoying, the interpolated size is dependent on the string length of the tempdir, which we can't control.

I believe the correct approach is to use a scheduled task to perform the installation, which isn't subject to the string size limits, nor to the memory size problems.

**Comment by hh** [comment]
A scheduled task would be interesting to monitor via a  single command, but I'm sure it can be done in under the max command size.

Until we get there, I think we should consider reducing the size of this file to fix at least a few use cases.

**Comment by hh** [comment]
Maybe we could use [Chef::Provisioning::Transport::WinRM#write_file](https://github.com/chef/chef-provisioning/blob/4638bdf99e048452b5b80e06c118ba2a0a0132a3/lib/chef/provisioning/transport/winrm.rb#L55) (which chunks by default)  to write the install command out to a file, then execute that via scheduled task.

**Comment by thommay** [comment]
Yes, that's the plan. I'm closing this PR since the work is mostly in chef/chef-provisioning#410

**Pull request closed without merging**
