### PR TITLE
updated powershell template to support airgapped artifact environment…

### PR DESCRIPTION
**Pull request by Romascopa**
…. Will be used by chef_client_updater

Signed-off-by: Lance Robbins <lance.robbins@delaware.gov>

## Description
updated powershell template to support airgapped artifact environment…

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by Romascopa** [comment]
Looks like the automated checks have some issues outside of my control. For example a DCO is there.

buildkite doesn't look related to my file edit at all.

**Comment by miah** [comment]
> Looks like the automated checks have some issues outside of my control. For example a DCO is there.

Its because your last commit is missing the sign-off.

**Comment by Romascopa** [comment]
sign-off fixed...

**Comment by Romascopa** [comment]
Looks like the pipeline auto-checks have some bugs in them (creating/using filenames that are TOO long). May need to manually push this through.

**Comment by tas50** [comment]
Thanks for fixing up the DCO here @Romascopa

**Pull request merged**
