### PR TITLE
revert powershell perf tuning changes. breaks older supported version…

### PR DESCRIPTION
**Pull request by wrightp**
…s of windows platforms

Signed-off-by: Patrick Wright <patrick@chef.io>

### CODE REVIEW

**Comment by wrightp** [comment]
@piyushawasthi FYI

**Comment by piyushawasthi** [comment]
@wrightp : Look like PR: https://github.com/chef/mixlib-install/pull/226 already merged in `Master` also I can't directly push on your branch `pw/revert-dae224` due to permission issue. `remote: Permission to chef/mixlib-install.git denied to piyushawasthi`. So I'll create New PR  https://github.com/chef/mixlib-install/pull/228 for that.

**Comment by piyushawasthi** [comment]
Relevant PR: https://github.com/chef/mixlib-install/pull/228

**Comment by wrightp** [comment]
Fixed in master

**Pull request closed without merging**
