### PR TITLE
Adding support for Cisco Nexus and IOS-XR devices

### PR DESCRIPTION
**Pull request by adamleff**

### CODE REVIEW

**Comment by adamleff** [comment]
Ping @schisamo, @patrick-wright, @thommay, @jtimberman - please let me know if you have any questions or suggestions.  This is to support the PartnerEng work with Cisco.

**Comment by scotthain** [comment]
Verified this will work with the Cisco builder image, at the very least :)

:+1:

**Comment by lamont-granquist** [comment]
yeah, this is just the same omnitruck PR ported here right?

**Comment by adamleff** [comment]
@lamont-granquist that's correct.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by patrick-wright** [comment]
:+1:

**Pull request merged**
