### PR TITLE
Add Train to product matrix

### PR DESCRIPTION
**Pull request by jaymalasinha**
Signed-off-by: Jaymala Sinha <jsinha@chef.io>

Add Inspec Train to the product matrix

## Description
Add train to the product matrix

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by marcparadise** [comment]
Do we have a downloadable train artifact now?

**Comment by jaymalasinha** [comment]
> Do we have a downloadable train artifact now?

No.  But it fails to create expeditor github release when `train` is not in the product matrix.  There could be a another way to solve this if `train` should not belong here.

**Comment by marcparadise** [comment]
Cool, it would be good to include that in the commit message so we have record of why it was added.

**Comment by tas50** [comment]
This seems like the wrong way to solve this issue. If we add it to the product matrix then the CLI will attempt to download it, but we don't have a package for train and never will.

**Comment by miah** [comment]
This PR should address the issue in expeditor

https://github.com/chef/expeditor/pull/1182

**Comment by jaymalasinha** [comment]
Thank you all for your reviews and comments.  I will look at fixing this within expeditor as adding train here might create an issue with the CLI

**Pull request closed without merging**
