### PR TITLE
Make Chef omnitruck endpoint configurable

### PR DESCRIPTION
**Pull request by bdwyertech**
## Description
Allow Chef Omnitruck endpoint to be configurable.  Went down the rabbit hole pretty deep trying to pass this from test-kitchen but can't find a way.

## Related Issue
https://github.com/test-kitchen/test-kitchen/issues/1698

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by lamont-granquist** [comment]
I think I'm :-1: on the env var here.  This should be a parameter that callers can specify to mixlib-install and that should be exposed as a public API and TK needs to be modified to support it.

**Comment by bdwyertech** [comment]
> I think I'm 👎 on the env var here. This should be a parameter that callers can specify to mixlib-install and that should be exposed as a public API and TK needs to be modified to support it.

I'm with you, it's certainly ugly. This PR is really just to demonstrate the issue.  There is another constant elsewhere which has an undocumented env var override so I used the same method.

This must be resolved before the deprecated logic in Test-Kitchen can be removed, otherwise my org is borked (were a large enterprise customer).

**Comment by Tensibai** [comment]
Alternative approach in https://github.com/chef/mixlib-install/pull/340 (would allow to override the endpoint for specific products too)

**Comment by jaymzh** [comment]
@bdwyertech - I agree with the others we want a more robust solution here. Looks like #340 got dropped, so we've picked that back up, hopefully we can get something like that in ASAP. It seems like it was designed for Cinc's case, but can you confirm it'll solve the TK case?

**Comment by bdwyertech** [comment]
Ò

> @bdwyertech - I agree with the others we want a more robust solution here. Looks like #340 got dropped, so we've picked that back up, hopefully we can get something like that in ASAP. It seems like it was designed for Cinc's case, but can you confirm it'll solve the TK case?

If #340 was merged, it looks like it would resolve this issue as well.

**Comment by tpowell-progress** [comment]
Closing in favor of #340

**Pull request closed without merging**
