### PR TITLE
Fix version detection in windows #16

### PR DESCRIPTION
**Pull request by dissonanz**

### CODE REVIEW

**Comment by schisamo** [comment]
Looks reasonable to me. Can you give things a review @patrick-wright @sersut @jaym?

**Comment by jaym** [comment]
:+1:

**Comment by patrick-wright** [comment]
@thommay Can you please review this change before we merge?

**Comment by thommay** [comment]
:+1:

**Comment by mwrock** [comment]
:-1:

**Comment by mwrock** [comment]
:+1:

**Comment by sersut** [comment]
Thanks @dissonanz. :+1: 

One thing to keep in mind is that we have moved the logic that uses these files under `Mixlib::Install::ScriptGenerator` since `0.8.0.alpha.0` release. I wonder if this is a blocker for many @thommay. In that case we should probably release a `0.7.1`. Otherwise we will get this out with the next alpha release of `0.8.0` which will eventually become `1.0.0` when we finish our rehaul. 

Let us know your thoughts on releasing this @thommay / @dissonanz.

**Comment by thommay** [comment]
hm, we should probably release this as a `0.7.1` I suppose - but I don't know how much this is affecting people.

**Comment by cheeseplus** [comment]
+1

**Comment by patrick-wright** [comment]
This patch was applied to a branch from the 0.7.0 release.  0.7.1 is tagged, and has been published to rubygems.org

**Pull request closed without merging**
