### PR TITLE
[WIP] ScriptGenerator

### PR DESCRIPTION
**Pull request by patrick-wright**
Not in a working state.  PR created for review and discussion.

### CODE REVIEW

**Comment by sersut** [comment]
This is good. Exactly what I was thinking. 

- We should update the `README.md` with the instructions to use the `ScriptGenerator` class. 
- We should fix the tests so this PR is mergable.

**Comment by patrick-wright** [comment]
@sersut Let me know whether this is on the right track.  I believe we are maintaining existing functionality while working in parallel so refactors can be done incrementally.  Should I be breaking `Mixlib::Install.install_command` at this point or should we allow a passthrough that calls `ScriptGenerator`'s `#install_command`?  I'm cool with breaking it in master though!

**Comment by sersut** [comment]
I think for now we can remove `install_command` from the main class of `Mixlib::Install`. 

This is a breaking change and we will make sure kitchen and provisioning are well locked before release.

**Comment by patrick-wright** [comment]
updated the PR change in PR 11.  Closing this PR.

**Pull request closed without merging**
