### PR TITLE
Add Chef Automate to the product matrix

### LINKED ISSUE #123: Add chef automate support
I don't see chef automate in ProductMatrix (https://github.com/chef/mixlib-install/blob/master/lib/mixlib/install/product.rb#L170) so I assume its currently not supported.

Was hoping to use https://github.com/chef-cookbooks/chef-ingredient eventually to install chef automate (https://downloads.chef.io/automate/).

### PR DESCRIPTION
**Pull request by schisamo**
This fixes #123.

/cc @chef/engineering-services @poliva83

### CODE REVIEW

**Comment by scotthain** [comment]
👍

**Comment by yzl** [comment]
👍

**Comment by wrightp** [comment]
nice dude 👍

**Comment by sersut** [comment]
👍

**Pull request merged**
