### PR TITLE
Fix chefstyle violations

### PR DESCRIPTION
**Pull request by mwrock**

### CODE REVIEW

**Comment by scotthain** [comment]
👍 Thanks!!

**Comment by schisamo** [comment]
@mwrock Can we attempt to remove the `rubocop.yml` file in this PR also? We shouldn't need that file now that we use `chefstyle`.

**Comment by mwrock** [comment]
just whacked rubocop.yml

**Comment by scotthain** [comment]
@chef/engineering-services for some more reviews

**Comment by schisamo** [comment]
👍

**Comment by yzl** [comment]
👍

**Comment by wrightp** [comment]
These changes should be part of the package-router branch. I'm 👍 on this

**Pull request merged**
