### PR TITLE
Return chef.bintray.com based urls for freebsd 9 artifacts.

### PR DESCRIPTION
**Pull request by sersut**
/cc: @chef/engineering-services 

* Fixes https://github.com/chef/mixlib-install/issues/91

Need to update mixlib-install in omnitruck to fix https://github.com/chef/omnitruck/issues/170 once this is merged.

### CODE REVIEW

**Comment by patrick-wright** [comment]
:ship:

**Comment by schisamo** [comment]
Does any of our test data exercise the FreeBSD 9 path now?

**Comment by sersut** [comment]
@schisamo Yeah. `:latest` without platform information gets us a list of things. That includes freebsd too.

**Comment by schisamo** [comment]
:+1: :shipit:

**Comment by scotthain** [comment]
:shipit: thank you!!!!!

**Pull request merged**
